spring:
  datasource:
    url: jdbc:h2:mem:${H2_DB_NAME}
    username: ${H2_DB_USER}
    password: ${H2_DB_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create # validate | update | create | create-drop
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
    settings:
      trace: false
      web-allow-others: false
